
- name: Stopping tomcat9 service
  systemd: state=stopped name=tomcat
  ignore_errors: True
  tags: tomcat

- name: Remove tomcat directory
  file: path="{{tomcat_install_path}}/{{tomcat_final}}" state=absent
  tags: tomcat


- name: Remove symlink tomcat directory
  file: path="{{tomcat_dir}}" state=absent
  tags: tomcat


- name: Remove tomcat service into systemd and reloading daemon
  file: path=/usr/lib/systemd/system/tomcat.service state=absent
  notify: systemd reload 
  tags: tomcat

- name: Remove the user 'tomcat'
  user:
    name: tomcat
    state: absent
    remove: yes
  tags: tomcat


- name: Remove the group 'tomcat'
  group:
    name: tomcat
    state: absent
  tags: tomcat


- name: Removing port 8080/tcp for Tomcat
  firewalld:
    port: 8080/tcp
    permanent: true
    immediate: true
    state: disabled
  notify: Reloading firewalld rules
  tags: tomcat
